---
apiVersion: v1
kind: Service
metadata:
  name: nzbget
spec:
  type: NodePort
  selector:
    app: nzbget
  ports:
    - name: web-ui 
      port: 6789
      targetPort: 6789
      protocol: TCP
  externalIPs:
    - 192.168.0.211
    - 192.168.0.221
    - 192.168.0.222
    - 192.168.5.223
    - 192.168.0.224
